version: '3.1'

services:
  app:
    image: 'exchangebot:latest'
    build:
      context: https://github.com/nannoda/exchange-rate-bot.git
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
    # By default the executable will be stored in /app
      - ./data:/app/data
    environment:
    # Required environment variables
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - EXCHANGE_RATE_API_KEY=${EXCHANGE_RATE_API_KEY}
      - EXCHANGE_FROM=${EXCHANGE_FROM}
      - EXCHANGE_TO=${EXCHANGE_TO}
      - COHERE_API_KEY=${COHERE_API_KEY}
    # Optional environment variables
      - DB_FILE=/app/data/bot.db

      - CHANNELS=${CHANNELS}
      - INTERVAL=${INTERVAL}
      - INCREASE_PROMPT_TEMPLATE=${INCREASE_PROMPT_TEMPLATE}
      - DECREASE_PROMPT_TEMPLATE=${DECREASE_PROMPT_TEMPLATE}
      - EQUAL_PROMPT_TEMPLATE=${EQUAL_PROMPT_TEMPLATE}
      - EXCHANGE_RATE_CHANGE_THRESHOLD=${EXCHANGE_RATE_CHANGE_THRESHOLD}
      - RUST_LOG=exchange_rate_bot=info